CREATE DATABASE IF NOT EXISTS mysql;
USE mysql;

CREATE TABLE IF NOT EXISTS seats (
  id INT NOT NULL AUTO_INCREMENT,
  user_id INT DEFAULT 0,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100),
  PRIMARY KEY (id)
);

INSERT INTO seats (user_id)
SELECT 0
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM seats WHERE user_id = 0 LIMIT 1);
